version: 2
registries:
  dhi:
    type: docker-registry
    url: dhi.io
    username: ${{ secrets.DOCKER_USER }}
    password: ${{ secrets.DOCKER_PASSWORD }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "npm"
    directory: "/service"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "docker"
    directory: "/"
    registries:
    - dhi
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
